# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/verpl/Documents/project/retrogame/bouncycube/bouncycube.srcs/sources_1/ip/clk60Hz/clk60Hz.xci
# IP: The module: 'clk60Hz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/verpl/Documents/project/retrogame/bouncycube/bouncycube.gen/sources_1/ip/clk60Hz/clk60Hz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk60Hz'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/verpl/Documents/project/retrogame/bouncycube/bouncycube.gen/sources_1/ip/clk60Hz/clk60Hz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk60Hz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/verpl/Documents/project/retrogame/bouncycube/bouncycube.gen/sources_1/ip/clk60Hz/clk60Hz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk60Hz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/verpl/Documents/project/retrogame/bouncycube/bouncycube.srcs/sources_1/ip/clk60Hz/clk60Hz.xci
# IP: The module: 'clk60Hz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/verpl/Documents/project/retrogame/bouncycube/bouncycube.gen/sources_1/ip/clk60Hz/clk60Hz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk60Hz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/verpl/Documents/project/retrogame/bouncycube/bouncycube.gen/sources_1/ip/clk60Hz/clk60Hz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk60Hz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/verpl/Documents/project/retrogame/bouncycube/bouncycube.gen/sources_1/ip/clk60Hz/clk60Hz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk60Hz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
