# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/woute/Desktop/rest/HBO/Projecten/Retrogame/RetroGame/VHDL/uart_communication/uart_communication.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2.xci
# IP: The module: 'blk_mem_gen_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/woute/Desktop/rest/HBO/Projecten/Retrogame/RetroGame/VHDL/uart_communication/bouncycube.gen/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/woute/Desktop/rest/HBO/Projecten/Retrogame/RetroGame/VHDL/uart_communication/uart_communication.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2.xci
# IP: The module: 'blk_mem_gen_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/woute/Desktop/rest/HBO/Projecten/Retrogame/RetroGame/VHDL/uart_communication/bouncycube.gen/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
