set_property IOSTANDARD LVCMOS33 [get_ports LED_Status]
set_property IOSTANDARD LVCMOS33 [get_ports Rx]
set_property IOSTANDARD LVCMOS33 [get_ports Tx]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN U16 [get_ports LED_Status]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN A15 [get_ports Rx]
set_property PACKAGE_PIN A14 [get_ports Tx]

set_property IOSTANDARD LVCMOS33 [get_ports sendButton]
set_property PACKAGE_PIN U18 [get_ports sendButton]
